EPS: 0.000000000001
FPS: 60
DISH_SIZE: 14 # cm


STAGES:
  - Juv

RESULTS_ROOT_DIR: "./results_epi_test"

LOCOMOTION_OUTDIR: "locomotion"
LOCOMOTION_PLOT_INTERVAL_MIN: 3

AREA_EXPLORED_OUTDIR: "area_explored"

FREQUENCY_OUTDIR: "frequency"
FREQUENCY_N: 24
FREQUENCY_WAVELET: cmorl1.5-1.0

PCA_FIT_ON_N: 8000
PCA_PLOT_N: 256
PCA_OUTDIR: pca_plots

MOVING_OUTDIR: moving_plots
MOVING_PLOT_TIME_SPAN_MIN: 30

ANGLE_RANGE_OUTDIR: angle_range
ANGLE_CORR_OUTDIR: angle_correlation


### Juv: ####

Juv:
  ROOT_DIR: "H:/projects/068_lora_tadpole/tadpose/notebooks/straight_movement_episodes/Juv"
               
  TRACK_SELECT_THRES: 0.9

  AREA_EXPLORED_NODE: "Tail_Stem"
  AREA_EXPLORED_BINS: 128


  ALIGN_CENTRAL: "Tail_Stem"
  ALIGN_TOP: "Heart_Center"
  
  LOCOMOTION_NODE: "Tail_Stem"
  LOCOMOTION_MOVING_THRESH: 1.2
  LOCOMOTION_TEMPORAL_SIGMA: 15
  LOCOMOTION_SPATIAL_SIGMA: 1
  LOCOMOTION_DC_SUBSAMPLE: 8

  # FREQ_MOVING_NODE: "Tail_Stem"
  # FREQ_MOVING_NODE_THRESH: 0.02
  FREQ_ACTIVE_THRESH: 0.1
  FREQ_ACTIVE_SMOOTH: 15
  FREQ_TEMP_ANGLE_SMOOTH: 0.1
  FREQ_FOR:     
    left_knee:
      - Left_Hip
      - Left_Knee
      - Left_Ankle
    left_ankle:
      - Left_Knee
      - Left_Ankle
      - Left_Foot
    left_foot:
      - Left_Ankle
      - Left_Foot
      - Left_toe

    right_knee:
      - Right_Hip
      - Right_Knee
      - Right_Ankle
    right_ankle:
      - Right_Knee
      - Right_Ankle
      - Right_Foot
    right_foot:
      - Right_Ankle
      - Right_Foot
      - Right_toe

  PCA_PARTS:
    Left_Leg: 
      - Tail_Stem
      - Left_Hip
      - Left_Knee
      - Left_Ankle
      - Left_Foot
      - Left_toe

    Right_Leg: 
      - Tail_Stem
      - Right_Hip
      - Right_Knee
      - Right_Ankle
      - Right_Foot
      - Right_toe

  ANGLE_RANGE_MOVING_NODE: "Tail_Stem"
  ANGLE_RANGE_MOVING_NODE_THRESH: 0.02
  ANGLE_RANGE_FOR:
    left_ankle:
      - Left_Knee
      - Left_Ankle # <- Angle here
      - Left_Foot
    left_knee:
      - Left_Hip
      - Left_Knee
      - Left_Ankle 
    left_foot:
      - Left_Ankle 
      - Left_Foot
      - Left_toe
    right_ankle:
      - Right_Knee
      - Right_Ankle
      - Right_Foot
    right_knee:
      - Right_Hip
      - Right_Knee
      - Right_Ankle
    right_foot:
      - Right_Ankle
      - Right_Foot
      - Right_toe

  ANGLE_CORR_ACTIVE_THRESH: 0.1
  ANGLE_CORR_ACTIVE_SMOOTH: 15
  ANGLE_CORR_TEMP_ANGLE_SMOOTH: 1
  ANGLE_CORR_WIN_SIZE: 31
  ANGLE_CORR_FOR:
    LR_ankle:
      - - Left_Knee
        - Left_Ankle  # <- Angle A
        - Left_Foot   #      |
      - - Right_Knee  #      |
        - Right_Ankle # <- Angle B
        - Right_Foot
    LR_knee:
      - - Left_Hip
        - Left_Knee
        - Left_Ankle 
      - - Right_Hip
        - Right_Knee
        - Right_Ankle
    LR_foot:
      - - Left_Ankle 
        - Left_Foot
        - Left_toe
      - - Right_Ankle
        - Right_Foot
        - Right_toe



  